FROM node:latest as builder
WORKDIR /usr/local/app
COPY package.json package-lock.json ./
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/v2testtask.client /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
